# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Tests

on:
  pull_request:
    branches: ["**"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - ruby-version: "2.5"
            gemfile: rails_5_2
          - ruby-version: "3.0"
            gemfile: rails_6_1
          - ruby-version: "3.0"
            gemfile: rails_7
          - ruby-version: "3.1"
            gemfile: rails_7_1
          - ruby-version: "3.3"
            gemfile: rails_main

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
          rubygems: latest
      - name: Run specs
        run: bundle exec rake spec
