name: Build

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["**"]

permissions:
  contents: read

jobs:
  rubocop:
    name: RuboCop
    runs-on: ubuntu-latest
    env:
      BUNDLE_ONLY: rubocop
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundler-cache: true
      - name: Run Rubocop
        run: bundle exec rubocop --parallel
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["3.0", "3.1", "3.2", "3.3"]
        gemfile:
          - rails_6_1
          - rails_7
          - rails_7_1
          - rails_main
        exclude:
          - ruby: "3.0"
            gemfile: "rails_main"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
          rubygems: latest
      - name: Run specs
        run: bundle exec rake spec
